# This file was generated by GoReleaser. DO NOT EDIT.
cask "audd" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "86404a25ffb63b07cb259f059df88a9ac4aeeec80c61de19e37d98a27926c78c"
      url "https://github.com/AudDMusic/audd-cli/releases/download/v#{version}/audd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "49d2c50c2d83fa53b9b2be8139e9520e85ec52d9830d12494a4a83e8b400b0d8"
      url "https://github.com/AudDMusic/audd-cli/releases/download/v#{version}/audd_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "be8a86713e11c9eacbf2e2b0d228eafcdc1ed78684e1a216f3d0bb928f5fcc13"
      url "https://github.com/AudDMusic/audd-cli/releases/download/v#{version}/audd_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3e33d7106ce0d4b8e3b288ec1a253b4bb7539cf0f059303dd4154e630ee6b461"
      url "https://github.com/AudDMusic/audd-cli/releases/download/v#{version}/audd_#{version}_linux_amd64.tar.gz"
    end
  end

  name "audd"
  desc "Recognize music in files, URLs, and streams with AudD"
  homepage "https://audd.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "audd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/audd"]
    end
  end

  # No zap stanza required
end
