# This file was generated by GoReleaser. DO NOT EDIT.
cask "audd" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "e969ba161308959b509fbb9b0596ec556bff7d24f44646d298cd06aa1e11dedc"
      url "https://github.com/AudDMusic/audd-cli/releases/download/v#{version}/audd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2b05b9784d49818c5bbdb926cae2acc545e87ee43c650f0c73851ca1aec026f5"
      url "https://github.com/AudDMusic/audd-cli/releases/download/v#{version}/audd_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1c50203fd78d0f97a506157916a70e320123e5f2224d3411f32a7f651120267a"
      url "https://github.com/AudDMusic/audd-cli/releases/download/v#{version}/audd_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4f4a4098346be31004dcccd1a3ced1e593811f6c4e4d2aa9309a42281b0dcb96"
      url "https://github.com/AudDMusic/audd-cli/releases/download/v#{version}/audd_#{version}_linux_amd64.tar.gz"
    end
  end

  name "audd"
  desc "Recognize music in files, URLs, and streams with AudD"
  homepage "https://audd.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "audd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/audd"]
    end
  end

  # No zap stanza required
end
