# This file was generated by GoReleaser. DO NOT EDIT.
cask "audd" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "94f1df92104970ff146f5b178e769e3ee7ae74be1aa95296c88e0ac8553953e8"
      url "https://github.com/AudDMusic/audd-cli/releases/download/v#{version}/audd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "03bfe1c1c7187506074547746b7e2490a42b87d138256cf1e56a3f40de4d65ca"
      url "https://github.com/AudDMusic/audd-cli/releases/download/v#{version}/audd_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1e123d49c6cccda75d152e3faebd3cb42589073c55d053d56e45128809536910"
      url "https://github.com/AudDMusic/audd-cli/releases/download/v#{version}/audd_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2c1864336d6370f90211c22178473ed20974e5076608767437909ec8eb2c98d9"
      url "https://github.com/AudDMusic/audd-cli/releases/download/v#{version}/audd_#{version}_linux_amd64.tar.gz"
    end
  end

  name "audd"
  desc "Recognize music in files, URLs, and streams with AudD"
  homepage "https://audd.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "audd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/audd"]
    end
  end

  # No zap stanza required
end
